### ISSUE TITLE
Pulldown GPIO27 not working

### ISSUE THREAD

**Issue by JoopIdema** [mattcallow/CPC_PICOROM#7]
I build the project but it was not working. The CPC starts, but the PicoROM did not.

After a while I realized that the signals on the diode OR gate were not getting through. The output to GPIO27 was always high. I could see this on the scope. 

I than added a 2k2 pulldown resistor on the output of the OR gate and then it worked (!). 
I do not understand why the pulldown you enabled on the Pico for GPIO27 is not working.

I tried 3 different Pico’s boards, but none of them work without the 2k2 pulldown resistor.

I tried this on a CPC464 and a CPC6128. The PicoROM on the CPC64 is working perfectly (with the 2k2 resistor). On the CPC6128 it works but is not stable. For example: If I use the |PDIR command it works, but when I use the |ROMS command, the CPC6128 restarts or shows garble.

Any idea’s what I did wrong?

p.s. I used the original Pico board without the WIFI option.

**Comment by mattcallow** [comment]
Regarding the pull-down resistors, it looks like I've tried to simplify my design too much. From what I've read, it seems that the pull-up/down resistors are only really for unconnected pins. I also use a pull-up on GPIO22, so maybe this should be an external resistor as well. I must have got lucky when testing with my CPC464.

Did you try any other resistor values? I think it's a good idea to add external resistor, but 2k2 seems a bit low. Does 4k7 or even 10k work?

Regarding the CPC6128, this might be related to the internal DOS ROM. I don't have a 6128 to test with. Can you with nothing in slot 7 in the config file?

**Comment by JoopIdema** [comment]
Looking at the signal on GPIO22, I don’t think an external resistor is necessary. I tried it anyway (4k7), but it makes no difference on the CPC6128.

I also tried leaving slot 7 empty in the config file. This makes no difference. Even without the config file and only the CPC6128, BASIC and PicoROM ROM files the CPC6128 restarts when typing the |ROMS command. So is that hardware or software related, what do you think?

Regarding to GPIO27. I did try other resistor values, starting with 10k and then 4k7. But these did not work (signal still looked bad on the scope), but 2k2 did.
Might it be useful if I to try adding an OR gate using a 74LS32 instead of the diodes? See what that does?

**Comment by JoopIdema** [comment]
Just te make sure I build an OR gate with the a 74LS32 instead of using the 3 diodes. 
It works fine on the CPC464 but still the same  problem on the CPC6128. So it looks to me that this is software problem. The diode OR gate is fine, as long  as an external pulldown resistor is added.

**Comment by mattcallow** [comment]
Thanks for testing that. I will add the pulldown to the next revision.
I'll need to look into the 6128 problem a bit more. I only have a 464 myself so testing may be tricky.

**Comment by JoopIdema** [comment]
If you need me to test anything just let me know. Happy to help.

**Comment by WacKEDmaN** [comment]
just thought i might mention that the pullups on the pico has issues....
https://forums.raspberrypi.com/viewtopic.php?t=375631

**Comment by pelrun** [comment]
You mean "the RP2350 has gpios that incorrectly source current when in high-impedance mode", which is only on the Pico2, and is *not* a problem with the pullups (despite the original discussion while the fault was being diagnosed.)

Don't go doing fuzzy keyword matching on this stuff unless you're prepared to doublecheck the gritty details.

**Comment by WacKEDmaN** [comment]
> You mean "the RP2350 has gpios that incorrectly source current when in high-impedance mode", which is only on the Pico2, and is _not_ a problem with the pullups (despite the original discussion while the fault was being diagnosed.)
> 
> Don't go doing fuzzy keyword matching on this stuff unless you're prepared to doublecheck the gritty details.

youre right.. i posted here too quick sorry.. i should have deleted it.. (didnt realise ya can now!)

**Comment by mattcallow** [comment]
> If you need me to test anything just let me know. Happy to help.

Can you try the firmware from the issue7 branch. This does not emulate ROM7

**Comment by JoopIdema** [comment]
I tested it, bit it doesn't load the picorom.rom. Not on the 464 or the 6128. It does load the other roms though.

**Comment by mattcallow** [comment]
Since it only emulates roms 0-6, you will need to load picorom.rom into a slot between 1 and 6

**Comment by JoopIdema** [comment]
Ok, I loaded the picrom.rom in slot 6. Now it loads, but unfortunately still the same problem. When using the |roms command the CPC6128 restarts.

**Comment by mattcallow** [comment]
Hmm, that's odd. The |ROMS command is only reading from Pico memory. It's not changing any ROMs seen by the CPC.
Does the |ROMS command work on your 464?
Do other commands such as |LED,0 work on the 464 and 6128?
Do commands in other ROMS work? e.g. if you maxam installed, does |HELP work?

**Comment by JoopIdema** [comment]
Yes, the |ROMS command works on my 464.
Yes, other commands (|LED,0, LED,1, |PDIR) work on both my 464 and 6128.
Yes, commands in other ROMS work. I installed the maxam rom and |HELP is working.

I tried 2 different Pico's so that also is not the problem. Could there be something wrong with my 6128?
Any signal maybe I need to check on the scope?

**Comment by mattcallow** [comment]
I don't know what would be wrong with the 6128.
I've added multiple firmware files to the issue7 branch. These use different clock speeds for the pico. Could you try these please?
The default is 250MHz, I've created files from 200MHz to 270MHz. All of these work on my 464

**Comment by JoopIdema** [comment]
I tried al firmware files. They all work on the 6128 but the |ROMS command does not. It still restarts the 6128.
Just to rule it out, I swapped the Z80 cpu's between the 464 and the 6128. But the problem stays on the 6128.
I also scoped all signals on the 50 pin bus connector. I see no strange signals. 

Then I scoped the signals on the Pico and when touching the RUN signal with the probe the Pico reboots. I also touched it with the multimeter probes and then it also reboots. I pulled it high with a 1K resistor, but it still reboots when I put the probe on it. This also happens on the 464, so it maybe unrelated to the |ROMS problem.

**Comment by mattcallow** [comment]
Thanks for that. I think that rules out the clock speed of the Pico as being the issue. As you say, I don't think the RUN signal is related.
I've built a new firmware (in the issue7 branch) with some debug enabled. Please try this, then post the contents of the DEBUG.TXT file after running the |ROMS command
Note: This might wipe your USB storage on the pico, so make sure you have a copy of it first.

**Comment by JoopIdema** [comment]
[DEBUG.TXT](https://github.com/user-attachments/files/18314901/DEBUG.TXT)
Here is the debug.txt.

**Comment by mattcallow** [comment]
Did you get anything on the CPC display before it reset?
Are you running the English OS and Basic  ROMs?
It looks like the error might be in the z80 code, but the PDIR and ROMS command use the same code, so I don't really understand what is happening.

**Comment by mattcallow** [comment]
I have pushed another version of the firmware and ROM, with more debug and a small change to the z80 code.
Please try this one and post the DEBUG.TXT file again.

**Comment by JoopIdema** [comment]
[DEBUG.TXT](https://github.com/user-attachments/files/18328986/DEBUG.TXT)
New debug.txt uploaded. 
I made a video with my phone so you can see for yourself what happens when I use the |ROMS command.
https://youtu.be/eO6YZ-mAyA0
I am using the English OS and Basic ROMs.

**Comment by mattcallow** [comment]
Can you try without quickcmd rom?

**Comment by JoopIdema** [comment]
[DEBUG.TXT](https://github.com/user-attachments/files/18330094/DEBUG.TXT)
Debug.txt without the quickcmd rom.

**Comment by JoopIdema** [comment]
[DEBUG.TXT](https://github.com/user-attachments/files/18330889/DEBUG.TXT)
Startup of the 6128 takes a fwe seconds now and the |PROMS command makes the 6128 freeze/hang.

**Comment by mattcallow** [comment]
I think I know what the problem is, but I won't be able to fix it for a week or two.

**Comment by mattcallow** [comment]
Please try the latest firmware and picorom image from the branch. Debug is disable in this version, so no need to post the DEBUG.TXT file

**Comment by JoopIdema** [comment]
Yes!! It's working. Great job.

**Comment by mattcallow** [comment]
thanks for testing. I've merged the changes into the main branch.

**Comment by JoopIdema** [comment]
Looks like you forgot to remove the 7 ROMS limit form the firmware. Because I can only load 7 roms, that should be 12 right?

**Comment by mattcallow** [comment]
Are you using the firmware from the main branch? That should allow 12 ROMs (and has the fixes in it now)

**Comment by JoopIdema** [comment]
Yes, I am using the firmware form the main branch. It says FW: 3.1.1 / PicoROM 3.02. 

I use the |ROMSET command to activate the games1.cfg (see below).

At first I had the picorom.rom in slot 11, but that did not work (the picorom was not loaded). I moved it to slot 6 but the |ROMS command only shows ROM0 to 6

I tested it on both the CPC464 and the 6128.

![Image](https://github.com/user-attachments/assets/2a28eb36-0fe0-4264-95b2-a6dff0081fa0)

![Image](https://github.com/user-attachments/assets/8c7dbd89-228c-4fbd-a16d-0e7aeb61d264)

# Games1
L:OS_6128.ROM
0:BASIC_1.1.ROM
1:GAMES/Arkanoid.rom
2:GAMES/Boulderdash.rom
3:GAMES/Classic_Invaders.rom
4:GAMES/Donkey_Kong.rom
5:GAMES/Harrier.rom
6:picorom.rom
8:GAMES/Electro_Freddy.rom
9:GAMES/EGGRSX.ROM
10:GAMES/Moon_Buggy.rom
11:GAMES/Killer_Gorilla.rom

**Comment by JoopIdema** [comment]
Ok, ignore my previous comment. Just to be sure I reflashed the pico and now it works.

**Comment by gilmod714** [comment]
> Yes!! It's working. Great job.

.. hello @JoopIdema  .. can you please share your final working files ?!

I am having the same issues as you , and the latest firmware , isn't working on my cpc6128 

Thank you :)

**Comment by JoopIdema** [comment]
> > Yes!! It's working. Great job.
> 
> .. hello [@JoopIdema](https://github.com/JoopIdema) .. can you please share your final working files ?!
> 
> I am having the same issues as you , and the latest firmware , isn't working on my cpc6128
> 
> Thank you :)

Yoyushould ask Matt, he is the developer. But the firmware I am using is the latest he published.

**Comment by gilmod714** [comment]
@JoopIdema  .. the latest firmware doesn't work for me at all on 6128

Also, you are saying it worked for you on cpc6128 ?!

The developer went MIA , he also does NOT have 6128 for testing , only 464
